# This section defines the split condition for the data
multiFileSupport:
  Input: 1
  Output: 0

splitCondition:
  channelmode: GMP_OCA_PORT_20 # The channel mode for splitting the data
  splitmode: 2  # The channel mode's particular mode for the data splitting
  splitAtEnd: false  # Whether to split the data at the end or the start of the splitmode

# This section defines the range of data to be analyzed
data_range:
  ahead: 100  # The amount of time to analyze ahead of the trigger (in ms)
  behind: 200   # The amount of time to analyze behind the trigger (in ms)

# This section defines any conditional filtering for the data
condition:
  conditionExist: false  # Whether to apply a conditional filter to the data
  conditionalChannel: CMD_POS_BHG2_Z  # The channel to use for the conditional filter
  conditionValue: '<-70000'  # Only consider to split signal if split mode match AND conditional channel match the value

function:
  requireFunc: true
  applyChName:
    - ENC_POS_BHG2_Z
    - ENC_POS_BHG2_BF_VCM
    - BHG2_ADC_PORT_BF_CAL
  newChName:
    - ENC_POS_BHG2_Z
    - ENC_POS_BHG2_BF_VCM
    - BHG2_ADC_PORT_BF_CAL
  funcs:
    - convertRes
    - convertRes
    - ADC_convert
  funcsInput:
    - 0.5
    - 0.1
    - 1

# This section defines the channels to plot
plotChannel:
  plotlist:
    - ENC_POS_BHG2_Z
    - DAC_BHG2_Z
    - ENC_POS_BHG2_BF_VCM
    - BHG2_ADC_PORT_BF_CAL
    - GMP_OCA_PORT_20
    - GMP_OCA_PORT_27
    - GMP_OCA_PORT_28
